-- Run once in Supabase Dashboard → SQL Editor
-- Global ascending booking IDs for cart WhatsApp checkout (starts at #1349)

CREATE TABLE IF NOT EXISTS public.cart_bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1349 INCREMENT BY 1) PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.cart_bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Reserve booking id" ON public.cart_bookings;
CREATE POLICY "Reserve booking id"
  ON public.cart_bookings FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Read booking id after insert" ON public.cart_bookings;
CREATE POLICY "Read booking id after insert"
  ON public.cart_bookings FOR SELECT
  TO anon, authenticated
  USING (true);
